import Link from "next/link";
import { LegalLayout } from "@/components/legal-layout";
import { AGB_VERSION, PRIVACY_VERSION } from "@/lib/legal-documents";
import { LEGAL_VERSION, legalAddressLines, legalOperator } from "@/lib/legal";

export function ImprintEn() {
  return <LegalLayout eyebrow="Legal information" title="Legal notice" updated={LEGAL_VERSION}>
    <section><h2>Information under Section 5 DDG</h2><div className="legal-address">{legalAddressLines().map(line => <span key={line}>{line}</span>)}</div><p className="legal-note">“Kamilunavo” is the trading name used. The natural person named above is the service provider responsible for Reklaio.</p></section>
    <section><h2>Contact</h2><p>Email: <a href={`mailto:${legalOperator.email}`}>{legalOperator.email}</a></p><p>Electronic contact form: <Link href="/en/kontakt">open contact form</Link></p><p>You can send us a direct electronic message through the contact form. We reply to the email address provided there.</p></section>
    <section><h2>Business identification number</h2><p>Business identification number under Section 139c of the German Fiscal Code: DE464473083-00001</p></section>
    <section><h2>Responsible for content</h2><p>Where a person responsible for individual content must be named: {legalOperator.operatorName}, address as above.</p></section>
    <section><h2>Consumer dispute resolution</h2><p>We are not obliged and are currently not willing to participate in dispute resolution proceedings before a consumer arbitration board.</p></section>
    <section><h2>About the service</h2><p>Reklaio helps users organise, document and write about consumer cases. It does not replace individual legal advice and does not make a binding assessment of claims or necessary legal steps.</p></section>
  </LegalLayout>;
}

export function PrivacyEn() {
  return <LegalLayout eyebrow="Privacy" title="Privacy Policy" updated={PRIVACY_VERSION}>
    <section><h2>1. Controller</h2><div className="legal-address">{legalAddressLines().map(line => <span key={line}>{line}</span>)}<span>Email: {legalOperator.email}</span></div></section>
    <section><h2>2. Purposes of processing</h2><p>Reklaio processes personal data to provide user accounts, case files, documents, deadlines, tasks, letters, communication, support, subscriptions, withdrawals, security, backups and optional AI features.</p><p>No solely automated decision with legal or similarly significant effects is made. AI results are not applied automatically and letters are not sent without user approval.</p></section>
    <section><h2>3. Website and security logs</h2><p>When you access the service, we may process the IP address, time, requested address, HTTP status and browser or device information. Limited counters and pseudonymous keys protect sign-in, registration, checkout, contact and withdrawal functions against automated abuse.</p><p>The legal basis is Article 6(1)(f) GDPR. Our legitimate interests are security, stability, error analysis and abuse prevention.</p></section>
    <section><h2>4. Hosting and backups</h2><p>The application, database and private file storage are operated on a managed system at {legalOperator.hostingProvider} in {legalOperator.hostingCountry}. Database and uploaded files are backed up automatically to non-public storage.</p><p>Backups are used to recover from technical failures, loss or security incidents and are deleted after a defined retention period. Deleted data may remain in protected backups until the backup cycle expires. The legal bases are Article 6(1)(b) and (f) GDPR.</p></section>
    <section><h2>5. User account and mobile app</h2><p>We process your email address, optional display name, password hash, verification and session data, onboarding status, accepted legal versions, plan, subscription status, roles, quotas and any suspension status. Plain-text passwords are never stored.</p><p>The mobile app stores a random session token in protected operating-system storage. Biometric features are checked only by the operating system and are not sent to Reklaio. Local deadline notifications are scheduled on the device.</p></section>
    <section><h2>6. Case files, documents and communication</h2><p>Users can store case details, timeline entries, tasks, provider replies, deadlines, letters, email delivery data and documents. These may contain personal data relating to communication partners. Processing is based on Article 6(1)(b) GDPR. Users may upload only data they are legally entitled to use for their own case.</p></section>
    <section><h2>7. Email delivery</h2><p>For verification, password recovery, deadline reminders, contract and withdrawal confirmations, and user-initiated letters, we process sender, recipient, subject, delivery and technical delivery data. Email is currently delivered through one.com. The legal basis depends on the message purpose and may be Article 6(1)(b), (c) or (f) GDPR.</p></section>
    <section><h2>8. Contact form and support</h2><p>We process name, email, subject, message, time, optional account link and a pseudonymous IP key. Processing is based on Article 6(1)(b) GDPR for contract-related requests and otherwise Article 6(1)(f) GDPR.</p></section>
    <section><h2>9. Reklaio Pro on the web and Stripe</h2><p>Website subscriptions use Stripe. Reklaio sends the account email, internal user and order identifier, selected price, contract metadata and technical checkout data. Stripe processes payment, invoice, tax and transaction data.</p><p>Reklaio does not store complete card details. The recipients include Stripe Payments Europe, Limited, Dublin, its affiliates and processors. The legal bases are Article 6(1)(b) and (c) GDPR.</p></section>
    <section><h2>10. Mobile subscriptions through Apple, Google and RevenueCat</h2><p>iOS subscriptions use Apple In-App Purchase and Android subscriptions use Google Play Billing. Apple or Google process store-account, payment, tax, invoice, device and transaction data under their own policies. Reklaio receives no complete card or bank data.</p><p>RevenueCat is used to manage subscription entitlements across platforms. It receives a random internal Reklaio user ID, product and store details, purchase, renewal, cancellation and expiry status, environment and technical event identifiers. The email address is not used as the RevenueCat user ID.</p></section>
    <section><h2>11. Withdrawals and refunds</h2><p>For online withdrawals, we store name, email, optional contract reference, declaration and processing times, and optionally link the request to an account. Mobile-store refunds are generally requested and handled through Apple or Google. The legal bases are Article 6(1)(b) and (c) GDPR.</p></section>
    <section><h2>12. Optional AI features</h2><p>AI document analysis and AI letters are optional Pro features. After separate consent, the selected document or confirmed case data and a technical instruction are sent to the OpenAI API.</p><p>For users in the EEA, the recipient is generally OpenAI Ireland Ltd., Dublin, including its affiliates and processors. The legal basis is Article 6(1)(a) GDPR and, for special categories of personal data, Article 9(2)(a) GDPR. Consent can be withdrawn for the future.</p><p>Under its published API terms, OpenAI does not use API content for model training by default. Reklaio requests disabled application storage where supported.</p></section>
    <section><h2>13. AI quotas and cost control</h2><p>To enforce plans, we process the type, time and status of AI operations, monthly usage, individual limits and technical error codes. The legal bases are Article 6(1)(b) and (f) GDPR.</p></section>
    <section><h2>14. Administration and system events</h2><p>Administrators can manage accounts, plans, limits, suspensions, support requests, withdrawals, billing events and system status. Administrative changes are logged. Payment, store-sync, email or backup failures may be stored as system incidents.</p></section>
    <section><h2>15. Cookies, local storage and Google Ads</h2><p>Reklaio uses essential cookies and local storage for sessions, security and user preferences. With your voluntary consent, Google tags may measure page views, registrations and Pro purchases from Google Ads. Without consent, the Google tag is not loaded. You can change your selection using Cookie settings. The legal basis for optional measurement is Article 6(1)(a) GDPR.</p></section>
    <section><h2>16. Retention and deletion</h2><p>Account and case data are stored while the account is active and deleted following an effective deletion request unless legal retention or proof obligations apply. Security, contract, billing and audit data may be retained for the applicable statutory period. AI analyses can be deleted separately.</p></section>
    <section><h2>17. Recipients and international transfers</h2><p>Data is shared only where necessary with hosting, email, payment, store, subscription-management and AI providers. Where data is processed outside the EEA, the applicable adequacy decision, standard contractual clauses or another lawful safeguard is used.</p></section>
    <section><h2>18. Your rights</h2><p>Subject to the legal requirements, you have rights of access, rectification, erasure, restriction, portability and objection, and may withdraw consent for the future. Contact us at <a href={`mailto:${legalOperator.email}`}>{legalOperator.email}</a> or through the <Link href="/en/kontakt">contact form</Link>. You may also complain to a data-protection authority.</p></section>
    <section><h2>19. Security and changes</h2><p>Safeguards include encrypted transmission, password hashes, random session tokens, access controls, private file storage, protected webhooks, rate limits, backups and administrative audit logs. This policy is updated when features, providers or legal requirements change.</p></section>
  </LegalLayout>;
}

export function TermsEn() {
  return <LegalLayout eyebrow="Contract rules" title="Terms and Conditions" updated={AGB_VERSION}>
    <section><h2>1. Provider and scope</h2><p>These Terms apply to consumer use of Reklaio. The provider is {legalOperator.businessName}, proprietor {legalOperator.operatorName}. Different terms apply only if expressly confirmed.</p></section>
    <section><h2>2. Purpose of Reklaio</h2><p>Reklaio is a digital organisation and writing aid for private consumer cases. Users can manage case files, evidence, events, tasks, deadlines, provider replies and letters.</p><p>Reklaio does not provide legal advice or representation and does not guarantee a claim or the success of a letter or escalation.</p></section>
    <section><h2>3. Reklaio Free</h2><p>The Free plan includes the core functions listed on the pricing page, including case files, document storage, deadlines, tasks, templates, email, the case assistant and PDF export. Reasonable technical limits may protect the service.</p></section>
    <section><h2>4. Reklaio Pro</h2><p>Reklaio Pro adds optional AI document analysis and individual AI letters. Monthly allowances and the current scope are shown before purchase.</p></section>
    <section><h2>5. Registration</h2><p>A personal account is required for protected functions. Users must provide accurate information, protect their access details and inform Reklaio immediately of suspected misuse.</p></section>
    <section><h2>6. Forming a Pro contract</h2><p>Before a paid order, Reklaio shows the service, total price, billing period, automatic renewal and cancellation terms. The contract begins once the order and payment are successfully confirmed and Pro status is sent to Reklaio.</p><p>Website payments use Stripe; iOS uses Apple In-App Purchase and Android uses Google Play Billing. Store payment, billing and refund rules also apply to store purchases.</p></section>
    <section><h2>7. Prices and payment</h2><p>The total price highlighted immediately before ordering applies. For mobile purchases, the localised price shown by Apple or Google applies. Reklaio stores no complete card, bank or store-payment data.</p></section>
    <section><h2>8. Term, renewal and cancellation</h2><p>Pro runs for the displayed billing period and renews automatically unless cancelled before the next renewal date. Web subscriptions are managed through Stripe; Apple and Google subscriptions through the relevant store account.</p><p>Deleting a Reklaio account does not automatically cancel a store subscription.</p></section>
    <section><h2>9. Withdrawal and refunds</h2><p>For contracts made directly on the Reklaio website, cancellation information and a model form are available under <Link href="/en/widerruf">Withdrawal</Link>. Apple and Google handle billing, cancellation and refund requests for their purchases. Mandatory consumer rights remain unaffected.</p></section>
    <section><h2>10. AI allowances and fair use</h2><p>AI features are subject to the monthly allowances shown in the plan or account. Failed technical operations are generally not counted. Reklaio may protect the service against automated or abusive mass use.</p></section>
    <section><h2>11. User content</h2><p>Users are responsible for data they enter, upload, accept and send. They may process only data and documents they are legally entitled to use.</p><ul><li>No unlawful, deceptive or abusive content</li><li>No forged evidence or knowingly false facts</li><li>No malware or unlawful bulk messages</li><li>No sharing of personal access credentials</li></ul></section>
    <section><h2>12. AI output</h2><p>AI results may be incomplete or incorrect. Detected document values are not applied without review and AI letters are not sent automatically. Users must check original documents, facts, amounts, addresses, deadlines and text in full.</p></section>
    <section><h2>13. Email delivery</h2><p>The user chooses the recipient, content, subject, attachments and deadlines. Reklaio provides technical transfer to the email provider, not guaranteed receipt or a response.</p></section>
    <section><h2>14. Availability, maintenance and changes</h2><p>Continuous availability is not guaranteed. Maintenance, security measures, faults and external providers may temporarily affect the service. Material adverse changes to paid services will be announced with reasonable notice.</p></section>
    <section><h2>15. Suspension</h2><p>Accounts may be temporarily suspended for a concrete suspicion of misuse, serious security risks, payment problems or material breach. Where possible, the user can comment or remedy the issue.</p></section>
    <section><h2>16. Liability</h2><p>Liability is unlimited for intent, gross negligence, injury to life, body or health, and where mandatory law requires it. For slight negligence involving essential contractual duties, liability is limited to foreseeable typical damage. Otherwise, liability for slight negligence is excluded where permitted.</p><p>Reklaio is not liable for the legal accuracy of a user decision or successful enforcement of a claim.</p></section>
    <section><h2>17. Privacy and backups</h2><p>Details are in the <Link href="/en/datenschutz">Privacy Policy</Link>. Users should also keep important documents outside Reklaio and export them before deleting an account.</p></section>
    <section><h2>18. Final provisions</h2><p>German law applies. For consumers, this choice does not remove mandatory protection under the law of their country of habitual residence.</p><p>If one provision is invalid, the remaining provisions remain effective. Contact: <a href={`mailto:${legalOperator.email}`}>{legalOperator.email}</a> or <Link href="/en/kontakt">contact form</Link>.</p></section>
  </LegalLayout>;
}

export function AccountDeletionEn() {
  return <LegalLayout eyebrow="Privacy" title="Delete your Reklaio account" updated={PRIVACY_VERSION}>
    <section><h2>Delete your account and associated data</h2><p>You can start deletion in the mobile app under “Account & Security” or through account settings on the website.</p><p>Your account and associated case files, deadlines, timeline entries and uploaded documents are permanently removed unless statutory retention requirements apply.</p></section>
    <section><h2>Delete through the app</h2><ol><li>Open “Account” in Reklaio.</li><li>Select “Delete account and data”.</li><li>Confirm using your current password and the word “DELETE”.</li></ol></section>
    <section><h2>Delete in your browser</h2><p>Sign in to <Link href="/en/einstellungen">web account settings</Link> and use the “Delete account” section.</p></section>
    <section><h2>No longer have access?</h2><p>Email your deletion request from the address used for your Reklaio account to <a href={`mailto:${legalOperator.email}`}>{legalOperator.email}</a>. We may request proof that you own the account.</p></section>
    <section><h2>Subscriptions and account deletion</h2><p>An active Stripe subscription made on reklaio.de must be cancelled through web account settings before account deletion. Apple or Google subscriptions do not prevent immediate account deletion, but are not cancelled automatically and must be cancelled separately in the relevant store.</p><p>Billing, contract or security data may remain where legally required. Deleted content may remain in protected backups until the backup cycle expires.</p></section>
  </LegalLayout>;
}
