import { LegalLayout } from "@/components/legal-layout";
import { PRIVACY_VERSION } from "@/lib/legal-documents";
import { legalAddressLines, legalOperator } from "@/lib/legal";

export default function PrivacyPage() {
  return (
    <LegalLayout eyebrow="Datenschutz" title="Datenschutzerklärung" updated={PRIVACY_VERSION}>
      <section><h2>1. Verantwortlicher</h2><div className="legal-address">{legalAddressLines().map(line=><span key={line}>{line}</span>)}<span>E-Mail: {legalOperator.email}</span></div></section>

      <section><h2>2. Zwecke der Verarbeitung</h2><p>Reklaio verarbeitet personenbezogene Daten zur Bereitstellung von Nutzerkonten, Fallakten, Dokumenten, Fristen, Aufgaben, Schreiben, Kommunikation, Support, Abonnements, Widerrufen, Sicherheit, Datensicherung und freiwilligen KI-Funktionen.</p><p>Es findet keine ausschließlich automatisierte Entscheidung mit rechtlicher oder vergleichbar erheblicher Wirkung statt. KI-Ergebnisse werden nicht automatisch übernommen und Schreiben werden nicht ohne Nutzerfreigabe versendet.</p></section>

      <section><h2>3. Website- und Sicherheitsprotokolle</h2><p>Beim Aufruf können IP-Adresse, Zeitpunkt, angeforderte Adresse, HTTP-Status sowie Browser- und Geräteinformationen verarbeitet werden. Für Login, Registrierung, Checkout, Kontakt und Widerruf werden begrenzte Zähler und pseudonymisierte Schlüssel eingesetzt, um automatisierten Missbrauch zu verhindern.</p><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse liegt in Sicherheit, Stabilität, Fehleranalyse und Missbrauchsschutz. Sicherheitszähler werden regelmäßig bereinigt.</p></section>

      <section><h2>4. Hosting und Datensicherung</h2><p>Anwendung, Datenbank und private Dateispeicher werden auf einem verwalteten System bei {legalOperator.hostingProvider} in {legalOperator.hostingCountry} betrieben. Datenbank und hochgeladene Dateien werden automatisiert in einem nicht öffentlich erreichbaren Backup-Speicher gesichert.</p><p>Backups dienen der Wiederherstellung nach technischen Fehlern, Verlust oder Sicherheitsvorfällen. Sie werden nach einer festgelegten Aufbewahrungszeit automatisch gelöscht. Einzelne gelöschte Inhalte können bis zum Ablauf dieser Sicherungsrotation technisch noch in verschlüsselten beziehungsweise geschützten Sicherungen enthalten sein.</p><p>Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b und lit. f DSGVO.</p></section>

      <section><h2>5. Nutzerkonto</h2><p>Verarbeitet werden E-Mail-Adresse, optionaler Anzeigename, Passwort-Hash, Bestätigungsstatus, Sitzungsdaten, Onboardingstatus, akzeptierte Rechtstextversionen, Tarif, Abonnementstatus, Rollen, Kontingentgrenzen und gegebenenfalls Sperrstatus. Klartextpasswörter werden nicht gespeichert.</p><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO; Sicherheits- und Verwaltungsdaten zusätzlich Art. 6 Abs. 1 lit. f DSGVO.</p></section>

      <section><h2>6. Fallakten, Dokumente und Kommunikation</h2><p>Nutzer können Falldaten, Chronikeinträge, Aufgaben, Anbieterantworten, Fristen, Schreiben, E-Mail-Versanddaten und Dokumente speichern. Diese Inhalte können auch personenbezogene Daten von Kommunikationspartnern enthalten.</p><p>Die Verarbeitung erfolgt gemäß Art. 6 Abs. 1 lit. b DSGVO. Nutzer dürfen nur Daten einstellen, die sie für ihren eigenen Fall rechtmäßig verwenden dürfen.</p></section>

      <section><h2>7. E-Mail-Versand</h2><p>Für Bestätigung, Passwort-Wiederherstellung, Fristerinnerungen, Vertragsbestätigungen, Widerrufsbestätigungen und vom Nutzer ausgelöste Schreiben werden Absender-, Empfänger-, Betreff-, Versand- und technische Zustelldaten verarbeitet. Der E-Mail-Versand erfolgt derzeit über one.com.</p><p>Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b, lit. c und lit. f DSGVO, abhängig vom konkreten Nachrichtenzweck.</p></section>

      <section><h2>8. Kontaktformular und Support</h2><p>Verarbeitet werden Name, E-Mail, Thema, Nachricht, Zeitpunkt, optional die Kontozuordnung sowie ein pseudonymisierter IP-Schlüssel. Im Admin-Center werden Bearbeitungsstatus und verantwortliche Bearbeitung protokolliert.</p><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO bei vertragsbezogenen Anfragen und ansonsten Art. 6 Abs. 1 lit. f DSGVO. Daten werden gelöscht, wenn sie für Bearbeitung, Missbrauchsschutz und Nachweise nicht mehr erforderlich sind.</p></section>

      <section><h2>9. Reklaio Pro und Stripe</h2><p>Für Reklaio-Pro-Abonnements wird Stripe eingesetzt. An Stripe werden Konto-E-Mail, interne Nutzer- und Bestellkennung, ausgewählter Preis, Vertragsmetadaten und technische Checkoutdaten übermittelt. Stripe verarbeitet Zahlungs-, Rechnungs-, Steuer- und Transaktionsdaten.</p><p>Reklaio speichert keine vollständigen Kartendaten. Gespeichert werden Stripe-Kunden-, Sitzungs- und Abonnementkennungen, Status, Laufzeit, Kündigungsstatus, angezeigter Preis sowie Zeitpunkt und Version der bestätigten AGB-, Datenschutz- und Widerrufsangaben.</p><p>Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b und lit. c DSGVO. Empfänger ist Stripe Payments Europe, Limited, Dublin, einschließlich eingesetzter verbundener Unternehmen und Unterauftragsverarbeiter.</p></section>

      <section><h2>10. Widerrufe</h2><p>Beim Online-Widerruf werden Name, E-Mail, optionale Vertragsreferenz, Erklärung, Eingangs- und Bearbeitungszeitpunkt sowie optional die Kontozuordnung gespeichert. Diese Daten dienen der Bearbeitung und dem Nachweis des Widerrufs.</p><p>Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b und lit. c DSGVO. Widerrufsdaten können entsprechend gesetzlicher Nachweis- und Aufbewahrungspflichten gespeichert werden.</p></section>

      <section><h2>11. Freiwillige KI-Funktionen</h2><p>KI-Dokumentanalysen und KI-Schreiben sind Pro-Funktionen, bleiben aber freiwillig. Nach gesonderter Zustimmung werden das ausgewählte Dokument oder bestätigte Falldaten zusammen mit einer technischen Anweisung an die OpenAI API übermittelt.</p><p>Empfänger ist für Nutzer im Europäischen Wirtschaftsraum grundsätzlich OpenAI Ireland Ltd., Dublin, einschließlich eingesetzter verbundener Unternehmen und Unterauftragsverarbeiter.</p><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. a DSGVO. Bei besonderen Kategorien personenbezogener Daten gilt zusätzlich Art. 9 Abs. 2 lit. a DSGVO. Die Einwilligung kann für die Zukunft widerrufen werden.</p><p>OpenAI verwendet API-Inhalte nach den veröffentlichten Bedingungen standardmäßig nicht zum Modelltraining. Reklaio fordert die Schnittstelle mit deaktivierter Anwendungsspeicherung an, soweit unterstützt. Gespeichert werden Analyseergebnis, Modell, Zustimmung, technische Antwortkennung, Status, Dateigröße und Nutzungszeitpunkt.</p></section>

      <section><h2>12. KI-Kontingente und Kostenkontrolle</h2><p>Zur Tarifdurchsetzung werden Art, Zeitpunkt und Status eines KI-Vorgangs, monatliche Nutzung, individuelle Limits und technische Fehlercodes verarbeitet. Reservierte Vorgänge werden bei technischen Abbrüchen nach kurzer Zeit als fehlgeschlagen markiert.</p><p>Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b und lit. f DSGVO. Das berechtigte Interesse liegt in Kostenkontrolle und Schutz vor missbräuchlicher Massennutzung.</p></section>

      <section><h2>13. Administration und Systemereignisse</h2><p>Administratoren können Konten, Tarife, Limits, Sperren, Supportanfragen, Widerrufe, Abrechnungsereignisse und Systemstatus verwalten. Administrative Änderungen werden mit Admin-Kennung, Zielkonto, Aktion, Zeitpunkt und sachbezogenen Details protokolliert.</p><p>Fehlgeschlagene Zahlungen, E-Mail-Probleme, Backupfehler und vergleichbare Betriebsereignisse können als Systemvorfall gespeichert werden. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b, lit. c und lit. f DSGVO.</p></section>

      <section><h2>14. Cookies, lokale Speicherung und Google Ads</h2><p>Reklaio verwendet technisch notwendige Cookies oder vergleichbare Speichermechanismen für Anmeldung, Sitzung, Sicherheit und die Speicherung der Datenschutz-Auswahl. Die Speicherung erfolgt gemäß § 25 Abs. 2 TDDDG sowie Art. 6 Abs. 1 lit. b und lit. f DSGVO.</p><p>Nur nach ausdrücklicher Einwilligung wird das Google-Tag für Reichweitenmessung und Google-Ads-Conversion-Tracking geladen. Dabei können insbesondere IP-Adresse, Browser- und Geräteinformationen, aufgerufene Adresse, Referrer, Google-Klickkennungen sowie Ereignisse wie eine erfolgreiche Registrierung oder ein abgeschlossener Reklaio-Pro-Checkout verarbeitet werden. Inhalte aus Fallakten, Dokumenten oder Schreiben sowie Konto-E-Mail-Adressen werden über diese Implementierung nicht an Google übermittelt.</p><p>Empfänger ist Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Eine Verarbeitung durch verbundene Unternehmen, insbesondere Google LLC in den USA, kann nicht ausgeschlossen werden. Rechtsgrundlagen sind § 25 Abs. 1 TDDDG und Art. 6 Abs. 1 lit. a DSGVO. Die Einwilligung ist freiwillig, kann über „Cookie-Einstellungen“ jederzeit mit Wirkung für die Zukunft widerrufen werden und das Google-Tag wird ohne Einwilligung nicht geladen.</p></section>

      <section><h2>15. Speicherdauer und Löschung</h2><p>Kontodaten und Fallinhalte werden grundsätzlich gespeichert, solange das Konto besteht oder der Inhalt benötigt wird. Nutzer können Dokumente, Schreiben, KI-Ergebnisse, Fälle und das Konto löschen. Abrechnungs-, Vertrags-, Widerrufs-, Sicherheits- und Administrationsdaten können aufgrund gesetzlicher Pflichten oder berechtigter Nachweisinteressen länger gespeichert werden.</p><p>Backups werden rollierend gelöscht. Stripe verarbeitet Daten zusätzlich nach eigenen gesetzlichen und vertraglichen Aufbewahrungsregeln.</p></section>

      <section><h2>16. Empfänger</h2><ul><li>Hosting- und Infrastruktur-Anbieter,</li><li>one.com für E-Mail-Versand,</li><li>Stripe für Checkout, Zahlung, Abonnement und Rechnung,</li><li>OpenAI ausschließlich bei freiwillig aktivierten KI-Vorgängen,</li><li>Google ausschließlich nach Einwilligung für Reichweitenmessung und Google-Ads-Conversion-Tracking,</li><li>Behörden oder sonstige Stellen bei gesetzlicher Verpflichtung.</li></ul><p>Personenbezogene Daten werden nicht an Werbetreibende verkauft.</p></section>

      <section><h2>17. Rechte</h2><p>Im Rahmen der gesetzlichen Voraussetzungen bestehen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch. Einwilligungen können mit Wirkung für die Zukunft widerrufen werden.</p><p>Anfragen sind per <a href={`mailto:${legalOperator.email}`}>E-Mail</a> oder <a href="/kontakt">Kontaktformular</a> möglich. Außerdem besteht ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde.</p></section>

      <section><h2>18. Sicherheit und Änderungen</h2><p>Schutzmaßnahmen umfassen verschlüsselte Übertragung, Passwort-Hashes, zufällige Sitzungstoken, Zugriffskontrollen, private Dateispeicherung, signaturgeprüfte Stripe-Webhooks, Rate-Limits, Backups und administrative Audit-Protokolle.</p><p>Diese Erklärung wird angepasst, wenn Funktionen, Anbieter oder rechtliche Anforderungen geändert werden. Die aktuelle Version wird mit einem neuen Stand veröffentlicht.</p></section>
    </LegalLayout>
  );
}
